### ISSUE TITLE
Youtube, Clipart, Photoeditor not working

### ISSUE THREAD

**Issue by ExaconAT** [ONLYOFFICE/sdkjs-plugins#25] opened 2017-11-23 10:08 UTC
BUG

Youtube wont put in a video, Clipart wont find Cliparts and Photoeditor opens new frame with white Background and forces me to reload the website.

- I open a or create a document in nextcloud and onlyoffice shows me the document

- I click on Plugins and select the plugin i want

Should work

Using: Newest, Chrome, Firefox, Edge, Windows 10, Windows 7

Deleted and reinstalled plugins via Git...

**Comment by ShockwaveNN** [comment] 2017-11-23 10:26
Is there some errors in Browser Console? And look in log files for errors

**Comment by ExaconAT** [comment] 2017-11-23 10:35
No errors in Browser, only Spellcheck has 404 error

Server 1 NC -> Server 2 ONLYOFFICE Running with Docker using NGINX.

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /spellchecker/doc/403_1511433060/c/info</pre>
</body>
</html>

With Server 1 NC + ONLYOFFICE Spellcheck works (running with Apache reverse Proxy)

**Comment by ExaconAT** [comment] 2017-11-23 10:42
`<VirtualHost *:443>
ServerName xxx

SSLEngine on
SSLCertificateFile "/etc/letsencrypt/live/xxxx/fullchain.pem"
SSLCertificateKeyFile "/etc/letsencrypt/live/xxxx/privkey.pem"

## Strong SSL Security
## https://raymii.org/s/tutorials/Strong_SSL_Security_On_Apache2.html

SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
SSLProtocol All -SSLv2 -SSLv3
SSLCompression off
SSLHonorCipherOrder on

## [Optional] Generate a stronger DHE parameter:
##   cd /etc/ssl/certs
##   sudo openssl dhparam -out dhparam.pem 4096
##
# SSLOpenSSLConfCmd DHParameters "/etc/ssl/certs/dhparam.pem"

SetEnvIf Host "^(.*)$" THE_HOST=$1
RequestHeader setifempty X-Forwarded-Proto https
RequestHeader setifempty X-Forwarded-Host %{THE_HOST}e
ProxyAddHeaders Off

ProxyPassMatch (.*)(\/websocket)$ "ws://localhost:8000/$1$2"
ProxyPass / "http://localhost:8000/"
ProxyPassReverse / "http://localhost:8000/"
</virtualhost>`

Thats the local install Machine (NC + Docker with Onlyoffice), no problem if i would know how to remove the plugins + spellcheck must work.

**Comment by ShockwaveNN** [comment] 2017-11-23 11:13
Ok, our staff working on reproducing this issue, I close this bug and leave https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/84

**Comment by agolybev** [comment] 2017-11-23 11:18
Duplicate of https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/84

**Closed by agolybev** 2017-11-23 11:18 UTC
