### ISSUE TITLE
ZOTERO adding a citation

### ISSUE THREAD

**Issue by VBoudry** [ONLYOFFICE/sdkjs-plugins#166] opened 2022-03-04 08:29 UTC
**Do you want to request a *feature* or report a *bug*?**
Good question, sounds like a bug, as a key feature is missing.

**What is the current behavior?**
There is no button to add a citation, only one to add a bibliography item.
What we have is described in https://api.onlyoffice.com/plugin/example/zotero

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I expect the "normal" ZOTERO behaviours: https://www.onlyoffice.com/en/app-directory/zotero
[insert a citation] somewhere in the text and insert bibliograhy.

**Which versions of sdkjs-plugins, and which browser / OS are affected by this issue? Did this work in previous versions of sdkjs-plugins?**
FF98 on OSX, OnlyOffice 7.0.1

**Comment by ShockwaveNN** [comment] 2022-03-04 08:31
Hi, this is duplicate of https://github.com/ONLYOFFICE/plugin-zotero/issues/19#issuecomment-1033686023

**Closed by ShockwaveNN** 2022-03-04 08:31 UTC
