### ISSUE TITLE
call to callCommand with different selections

### ISSUE THREAD

**Issue by lorenzoale** [ONLYOFFICE/sdkjs-plugins#174] opened 2022-09-12 09:37 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I need to get the content of a given control content with a given tag, let's say tag={content}. To do this I just remove all other elements from the document, but first I copy the content control. Then, after removing all elements I insert the control content. 
The problem:

1. is that when there is an image inside this content control, and the image is selected (because it was the last action that the user did), it just removes everything. 

2. In a similar way, if the user selected some content control, it does not remove anything.

To avoid this I just moved the cursor by means of the plugin method, but I wonder is this could not be solved other way. 

```js
window.Asc.plugin.executeMethod("MoveCursorToEnd",
		[true],
		function(){
				window.Asc.plugin.callCommand(
					function() {
						var oDocument = Api.GetDocument();
						var contenu_CC=null;
						var aContentControls = oDocument.GetAllContentControls();
						for (var i = 0; i < aContentControls.length; i++) {
							var tagName=aContentControls[i].GetTag();
							if (tagName== "{content}"){
								contenu_CC=aContentControls[i];
							}
						}
						oDocument.RemoveAllElements();
						oDocument.InsertContent([contenu_CC]);
					},
					false,
					true,
					function(){
						window.parent.Common.Gateway.sendInfo (
							{
								request: curr_request,
								args : { only_content: true }
							}
						);
					}
				);
			}
		);
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions of sdkjs-plugins, and which browser / OS are affected by this issue? Did this work in previous versions of sdkjs-plugins?**
 7.1.1

**Comment by askonev** [comment] 2022-09-12 19:21
@lorenzoale Hi! Yes, at the moment there is a technical limitation that you cannot change the content control while it is selected. 

1. _is that when there is an image inside this content control, and the image is selected (because it was the last action that the user did), it just removes everything._

I could not reproduce this problem. Can you send a test example of the document and the plugin on which this scenario is reproduced?

2. _...but I wonder is this could not be solved other way._

I think at the moment your solution is the best, if you want to implement in the body of the builder code first remove all elements, save one in memory and then put it back into the document.

**Comment by lorenzoale** [comment] 2022-09-14 08:45
@askonev I'm really sorry for the inconvenients. You do not need to test, I got the idea and I know how to overcome my problem. I edited the previous comment and tried to make it clearer anyway. Thanks again for your help.

**Comment by Rita-Bubnova** [comment] 2024-03-12 15:39
I close this issue. Feel free to comment or reopen it if you got further questions.

**Closed by Rita-Bubnova** 2024-03-12 15:39 UTC
Labels: waiting feedback
